language: ruby
rvm:
  - 2.4.0
env:
  - DB=pgsql
services:
  - postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bin/rake test
test:
  adapter: postgresql
  database: flashcards_test
before_script:
  - cp config/database.yml.travis config/database.yml
