language: ruby
rvm:
  - 2.4.0
env:
  - DB=pgsql
services:
  - postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bin/rake test
test:
  adapter: postgresql
  database: flashcards_test
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c "CREATE USER admin WITH PASSWORD 'admin';" -U postgres
  - psql -c 'CREATE DATABASE flashcards_test;' -U postgres
  - psql -c 'GRANT ALL PRIVILEGES ON DATABASE flashcards_test to admin;' -U postgres
  - psql -c 'ALTER DATABASE flashcards_test OWNER TO admin;' -U postgres
