development:
  secret_key_base: be590e273651323aa86f3cbd0287fbfddb19567d445d7a30f1aba127a725f28e44d3a0073b403ffb60b49b8119af3207f25784113879f8d6d57232ec07493e68
  sorcery_github_callback_url: http://127.0.0.2:3000/oauth/callback?provider=github
  sorcery_github_key: <%= ENV["SORCERY_GITHUB_KEY"] %>
  sorcery_github_secret: <%= ENV["SORCERY_GITHUB_SECRET"] %>

test:
  secret_key_base: 0d8aefa2812712f2480050deca1043238c5d76ab92e8165fbe25d41c2e965abaee2e07fabe7d73f6c977d0f9b9d854d0b6b99d454118518616faf10e5712fd73
  sorcery_github_key: <%= ENV["SORCERY_GITHUB_KEY"] %>
  sorcery_github_secret: <%= ENV["SORCERY_GITHUB_SECRET"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  sorcery_github_callback_url: <%= ENV["SORCERY_GITHUB_CALLBACK_URL"] %>
  sorcery_github_key: <%= ENV["SORCERY_GITHUB_KEY"] %>
  sorcery_github_secret: <%= ENV["SORCERY_GITHUB_SECRET"] %>
